import Html from '../assets/html.png';
import Css from '../assets/css.png';
import JavaScript from '../assets/javascript.png';
import react from '../assets/react.png';
import gitHub from '../assets/github.png';
import toolkit from '../assets/toolkit.jpg';
import router from '../assets/react-router.svg';
import tailwindCss from '../assets/Tcss.png';
import style from '../assets/atom (1).png';
import jira from '../assets/jira-3.svg';
export { Html, Css, JavaScript, react, gitHub, toolkit, router, tailwindCss,style,jira };
